
#!/bin/bash
#PBS -N workernode
#PBS -l nodes=1:Xeon:ppn=1
#PBS -l walltime=100:00:00
#PBS -q cmb
#PBS -l pmem=3gb
#PBS -l pvmem=3gb
#PBS -l mem=3gb
#PBS -l vmem=3gb
#PBS -j oe
#PBS -o /dev/null
#PBS -m p

cd ${PBS_O_WORKDIR}

source /home/cmb-08/fa/local/setup.sh
ulimit -s 8192
#IPEID=$(uuidgen)
#touch ".${IPEID}.restart"
ipengine --quiet 2> logs/workernode_${PBS_JOBID}.log

while [ -e ".workers.restart" ]
do
  sleep 1
  ipengine --quiet 2> logs/workernode_${PBS_JOBID}.log
done